from enum import Enum

class IconType(Enum):
    Alert_Thunderstorm = "Alert-Thunderstorm"
    Cloudy = "Cloudy"
    Danger_Hurricane = "Danger-Hurricane"
    Foggy = "Foggy"
    Heavy_Rain = "Heavy-Rain"
    Heavy_Snow = "Heavy-Snow"
    Light_Hurricane = "Light-Hurricane"
    Lightning = "Lightning"
    Light_Rain = "Light-Rain"
    Light_Snow = "Light-Snow"
    Mist = "Mist"
    Moderate_Rain = "Moderate-Rain"
    Moderate_Snow = "Moderate-Snow"
    Overcast = "Overcast"
    Partly_Cloudy = "Partly-Cloudy"
    Patchy_Rain = "Patchy-Rain"
    Sunny = "Sunny"
    Thunderstorm = "Thunderstorm"
    Last_Quarter = "Last-Quarter"
    Waning_Crescent = "Waning-Crescent"
    Waning_Gibbous = "Waning-Gibbous"
    New_Moon = "New-Moon"
    Waxing_Gibbous = "Waxing-Gibbous"
    First_Quarter = "First-Quarter"
    Waxing_Crescent = "Waxing-Crescent"
    Full_Moon = "Full-Moon"
    Sunrise = "Sunrise"
    Sunset = "Sunset"
    Unknown = ""